### ISSUE TITLE
Error when updating cartridge

### ISSUE THREAD

**Issue by AlexChesters** [icflorescu/openshift-cartridge-nodejs#13]
When pushing to the cartridge I get the following error:

```
remote: CLIENT_MESSAGE: Stopping Node.js application...
remote: CLIENT_RESULT: Warning! Could not stop Node.js application!
remote: An error occurred executing 'gear prereceive' (exit code: 1)
```

I'm going to assume this was introduced in #11

**Comment by AlexChesters** [comment]
D'oh, [this line](https://github.com/icflorescu/openshift-cartridge-nodejs/blob/master/bin/control#L63) should have been updated as part of #11. I'll get a hot fix for this now

**Comment by icflorescu** [comment]
Done. I've just refactored `start_command` into a standalone bash function and now everything seems to be fine. At least on a very simple test deployment.

Thanks again, and feel free to take a look at [this](https://github.com/icflorescu/openshift-cartridge-nodejs/issues/12) if / when you're in the mood ;-)
