### ISSUE TITLE
Allow specifying the npm version

### ISSUE THREAD

**Issue by phw** [icflorescu/openshift-cartridge-nodejs#22]
It would be great if one could specify the npm version to use similar to how you can specify the node version with a semver URL in `.openshift/NPM_VERSION_URL`.

**Comment by icflorescu** [comment]
Sounds interesting indeed. This should be fairly easy to implement, will have a look at it later this week. Feel free to make a PR if you find some spare time to build and test this meanwhile. [Here](https://github.com/icflorescu/openshift-cartridge-nodejs/blob/master/lib/util#L40)'s where `npm` gets installed.

**Comment by icflorescu** [comment]
This appears to be working now, so I'm closing the issue. Thanks a lot for PR & fix!
