### ISSUE TITLE
List this cart on hub.openshift.com?

### ISSUE THREAD

**Issue by ryanj** [icflorescu/openshift-cartridge-nodejs#28]
Hello icflorescu,
Would you be interested in listing this cart on the OpenShift Hub?

We used to have a form for submitting your cartridge or quickstart here: https://hub.openshift.com/quickstarts/new

The link seems to have gone bad.  I'll try to find a better one for you...

**Comment by icflorescu** [comment]
Hi ryanj,

Absolutely. Just drop me a line as soon as you have a working link again.

**Comment by luciddreamz** [comment]
Added manually from the Hub admin panel for now: [https://hub.openshift.com/quickstarts/243-node-js-latest](https://hub.openshift.com/quickstarts/243-node-js-latest)

**Comment by icflorescu** [comment]
Thanks guys, you're awesome!

Looks like I have edit access to the quickstart page, so I'll keep the documentation up to date.
