### ISSUE TITLE
Disable auto-update?

### ISSUE THREAD

**Issue by nyarenbee** [icflorescu/openshift-cartridge-nodejs#29]
Is there a way to control when to update to latest or not? May be adding something to hook so that we can control what version of node gets installed?

**Comment by icflorescu** [comment]
Yes, you can do so by setting the `NODE_VERSION_URL` environment variable or `.openshift/NODE_VERSION_URL` marker to a very specific version URL, such as `https://semver.io/node/resolve/4.3.2`.

**Comment by icflorescu** [comment]
Other people may raise the same question, so I've added this as an FAQ in README as well.

**Comment by icflorescu** [comment]
I assume the explanation is satisfactory, so I'm closing this.

**Comment by nyarenbee** [comment]
Thanks a lot.
