### ISSUE TITLE
When I make an instance i get a error

### ISSUE THREAD

**Issue by rkmax** [icflorescu/openshift-cartridge-nodejs#3]
![captura de pantalla de 2015-08-14 16-57-20](https://cloud.githubusercontent.com/assets/395707/9284881/aaa6193a-42a5-11e5-96e9-8f6c3408a296.png)

**Comment by icflorescu** [comment]
It's a warning, not an error.
I've noticed it in a project using mongoose, but in the end it looks like `node-gyp` does work as expected in `tmp/.node-gyp`.
