### ISSUE TITLE
inter-device move failed

### ISSUE THREAD

**Issue by icflorescu** [icflorescu/openshift-cartridge-nodejs#30]
The error below was reported by @UberActivist, anyone else came across it so far?

![oklkqtn](https://cloud.githubusercontent.com/assets/581999/13728805/4fd7055e-e92c-11e5-8c5e-748461c06bf8.png)

Don't have time to investigate right now, so any help would be appreciated. The problem looks like it's coming from [here](https://github.com/icflorescu/openshift-cartridge-nodejs/blob/master/bin/control#L18) but I'm not sure why `mv` fails...

**Comment by burib** [comment]
@icflorescu hi, yeah. I've also came across.

if I push to the repository and wait for it to restart, then usually it fails to restart, then I wait for a while and type `rhc app stop myAppName` then I got the same error.

**Comment by icflorescu** [comment]
@burib @UberActivist - I think I've fixed it.

Try to recreate your applications again and let me know how it goes.

Unfortunately there's no way to upgrade your existing deployments, so you'll have to do it from scratch...

**Comment by MoiraPrime** [comment]
I was finally able to get my Discord bot to run using it. So yay, I believe it's fixed. 
![image](https://cloud.githubusercontent.com/assets/11623577/14055065/a2907db4-f2ac-11e5-9b9b-9d9983316d3e.png)

**Comment by icflorescu** [comment]
Glad to hear!

**Comment by chenkehxx** [comment]
@UberActivist  I got the same error, how do you fix it?

**Comment by MoiraPrime** [comment]
@chenkehxx As far as I'm aware, I just recreated the app. There was an issue with an earlier version.

**Comment by icflorescu** [comment]
Yes, AFAIK there's no way to upgrade custom OpeShift cartridges, so you'll have to recreate your deployment.

**Comment by chenkehxx** [comment]
@UberActivist @icflorescu  Thanks
