### ISSUE TITLE
Help: Upload folder resets each time I deploy. Image Assets from User uploads get lost.

### ISSUE THREAD

**Issue by yudhir** [icflorescu/openshift-cartridge-nodejs#40]
I am a new user to openshift or cloud deployments, I really like this cartridge because it has latest 5.X node and mongo 3.X .
I don't know how this deployment works and the idea behind it. If I add images to the GIT repo , that might work , but I don't think you add assets to GIT. 

Any Help would be appreciated.

**Comment by mayank1love** [comment]
I think you need a .gitignore file in the uploads folder. This way your uploads folder will remain as it is even after git push of new codes.

**Comment by icflorescu** [comment]
@yudhir - you should **never** put user files (such as uploads) in the git repo dir, as they will be erased on `git push`. This is true not only for OpenShift, but generally for all PaaS environments allowing git deployments.

@mayank1love's solution could work, but it's kind of an unsafe hack. 

In our case, the **safe** place to put them is `env.DATA_DIR` (which is a shortcut to `env.OPENSHIFT_DATA_DIR`).

You can learn more in the OpenShift Online Documentation [here](https://access.redhat.com/documentation/en-US/OpenShift_Online/2.0/html/Cartridge_Specification_Guide/chap-Environment_Variables.html).

If you'll take a look at [lib/util](https://github.com/icflorescu/openshift-cartridge-nodejs/blob/master/lib/util) you'll see I'm storing the Node.js binaries in `${OPENSHIFT_DATA_DIR}.nodejs` for the same reason - I want them to be persistent across deployments.

As a side note, when working with temporary files you can also use `env.TMP` folder.
