### ISSUE TITLE
Can't recognize Budo

### ISSUE THREAD

**Issue by 0xTheProDev** [icflorescu/openshift-cartridge-nodejs#41]
main.js: 1st line:  var budo = require('budo');

```
at Function.Module._resolveFilename (module.js:339:15)

at Function.Module._load (module.js:290:25)

at Module.require (module.js:367:17)

at require (internal/module.js:20:19)

at Object.<anonymous> (/var/lib/openshift/5738bca57628e1b375000185/app-root/runtime/repo/main.js:1:74)

at Module._compile (module.js:413:34)

at Object.Module._extensions..js (module.js:422:10)

at Module.load (module.js:357:32)

at Function.Module._load (module.js:314:12)

at Function.Module.runMain (module.js:447:10)
```

**Comment by icflorescu** [comment]
Can you elaborate a bit? What is your setup? Do you have it in `package.json`? Did you encounter any problems or error messages during deployment?

And, just out of curiosity, why are you using `budo` on the server?

**Comment by yudhir** [comment]
dev dependencies are not built on openshift too!  If that could be the case?

**Comment by icflorescu** [comment]
Of course not. Modules are installed with `npm i --production`, so the ones in your `devDependencies` are **development**-related and will **not** be installed on the server. This is common practice across all PaaS providers.

I still don't understand why would you need something like `budo`, `browserify` or `webpack` on the server, but if you insist and you know what you're doing, you can put it in `dependencies` in `package.json`.

Does that answer your question?

**Comment by icflorescu** [comment]
@Progyan1997 - any thoughts on this?

**Comment by 0xTheProDev** [comment]
The problem has been solved. Due to unknown reason the server.js file was
treated as binary file. Using budo from api. Thank you all for your
concern. Kindly review and give feedback on this ~
www.swipe-bprogyan.rhcloud.com

I have changed the alias to
www.swipe.io
But it's not working.

Sorry for late reply.

Regards,
Progyan

**Comment by icflorescu** [comment]
Great, glad to hear it. Going to close the issue then.
