### ISSUE TITLE
"Force update"

### ISSUE THREAD

**Issue by itsfolf** [icflorescu/openshift-cartridge-nodejs#43]
I changed the NODE_VERSION_URL to 6.2.0, and restarted the app, but nothing updated.

**Comment by itsfolf** [comment]
Just created a random file and pushed it, fixed.

**Comment by icflorescu** [comment]
Yeah, that's a potential issue, maybe I should put a note about it in the readme. You need to actually do a push to trigger the installation of a new Node.js version.

I actually considered doing it automatically on each app restart, but I don't think the benefits would justify increasing the restart time. What do you think?
