### ISSUE TITLE
/info/ GET request makes it crash

### ISSUE THREAD

**Issue by gubarez** [icflorescu/openshift-cartridge-nodejs#44]
Not sure whether this is intended, but if the request is everything except 'gen' and 'poll' the app crashes.

**Comment by icflorescu** [comment]
Not intended, just a minor omission of my part. Will come up with a fix soon.

Bear in mind though, that everything in `usr/template` is nothing more than a quick-and-dirty "filler" application and you shouldn't try to derive patterns from it. In real life, one would replace it with an Express/Koa/Sails/etc-based application with proper error handling.
