### ISSUE TITLE
set NODE_PATH=.

### ISSUE THREAD

**Issue by rihannarickeminem** [icflorescu/openshift-cartridge-nodejs#45]
in my package.json  i have     "start": "NODE_PATH=. NODE_ENV=production node app.js" ...
in /app-root/logs/nodejs.log  line : 
nohup: failed to run command `NODE_PATH=.': No such file or directory
how can i set NODE_PATH ?
should i remove " NODE_ENV=production " ?
I've created some question on stackoverflow- [the Question](http://stackoverflow.com/questions/37775753/how-to-set-node-path-for-node-js-app-hosted-in-openshift)

**Comment by icflorescu** [comment]
Already replied on stackoverflow, but I'll paste it here for the benefit of other people having similar questions.

Having `"start": "node app.js"` in your `package.json` should be just enough.

If you take a look at [`bin/install`](https://github.com/icflorescu/openshift-cartridge-nodejs/blob/master/bin/install), you'll see that `NODE_ENV` is already set to `production` by default in the cartridge setup script.

Also, I'm not sure what you're trying to achieve by setting `NODE_PATH` to `.`. There's a single Node.js version installed.

If you're generally interested in how you can set custom environment variables in an OpenShift-deployed application, have a look at the docs [here](https://developers.openshift.com/managing-your-applications/environment-variables.html). Basically you'll have to use the `rhc` command-line utility like this:

```
$ rhc env set <Variable>=<Value> <Variable2>=<Value2> -a App_Name
```

Hope this answers your question.

**Comment by rihannarickeminem** [comment]
Thank you for answering, dear Ionut-Cristian Florescu. 

> I have line in main app.js file. There is folder named 'config', in the same directory with app.js, in folder config placed file index.js, file index.js have code with 'module.exports = Object.assign({ ...some conifg object... });' . When i delete NODE_PATH=. , node throws "Error: Cannot find module 'config' " .

That is why i've asked .

**Comment by icflorescu** [comment]
You're welcome, but I'm not sure I understand what you mean. I mean, I'm quite sure I **don't** understand what you mean.
