### ISSUE TITLE
Tag info with Express

### ISSUE THREAD

**Issue by IPWright83** [icflorescu/openshift-cartridge-nodejs#46]
Apologies to start with (technically this isn't an issue) but a request for "How do I get this working". If you could give me a pointer, or suggest a better place to ask this I will do.

I've hooked up the default cartridge to use `express` which is all fine and dandy. In doing this I noticed a bunch of 404 errors which is the polling of the tag info. From my understanding this is polling through to an openshift internal URL which is providing some sort of information. 

What I can't work out, is how do I "allow" these requests to go through, without `express` intercepting them and then rejecting them because there's no route set up? Or - do I need to set up a route and point it something else?

**Comment by IPWright83** [comment]
Managed to answer my own question. For anyone else trying to figure this out then use something along these lines:

```
"use strict";

let express = require('express');
let sysInfo = require('../utils/sys-info');
let router = express.Router();

router.route('/info/gen')
      .get(function(req, res) {
            res.json(sysInfo.gen());
      });

router.route('/info/poll') 
      .get(function(req, res) {
        res.json(sysInfo.poll());
      });

module.exports = router;
```

**Comment by icflorescu** [comment]
Glad you found the answer and sorry for the delayed reply.

I fail to see, though, why you'd want your server-side application to respond to those requests. In the end, `usr/template` is nothing more that a simple quick-and-dirty test application which you are supposed to switch with your own; there's nothing mandatory in there, there's nothing strictly OpenShift-related. You can safely discard everything, including the client-side Riot.js tag that polls the server.

**Comment by IPWright83** [comment]
@icflorescu I guess I just like statistics! I'm just building a small utility for myself so I'm happy keeping the current splash screen - that's kinda why I wanted to keep it on there.

**Comment by icflorescu** [comment]
:-)

Yeah, I know where you're coming from. Initially I was planning for a more eye-catching splash-screen for the sample application, but in the end couldn't find the time/energy/justification to actually do it.
