### ISSUE TITLE
Looking for feedback on changing the default URL to install the latest Node.js version

### ISSUE THREAD

**Issue by icflorescu** [icflorescu/openshift-cartridge-nodejs#48]
I'm not sure why, but [semver.io](https://semver.io/) is constantly lagging behind on correctly reporting the latest Node.js version.

As of June 21st 2016, [semver.io/node/stable](https://semver.io/node/stable) still says `5.1.11`, while in reality we're at `6.2.2`, which I'd say is stable enough. 

Therefore, I'm considering to switch the default semver URL to [semver.io/node/resolve/6](https://semver.io/node/resolve/6), which correctly reports `6.2.2`, but I'll wait a couple of days for user feedback before proceeding.

Please note that you'll still be able to use `5.1.11`, or generally lock your application to a specific version by expressly setting the `NODE_VERSION_URL` to something like `https://semver.io/node/resolve/5.1.11`.

**Comment by apihlaja** [comment]
I'd say the latest stable is still v4.. But thats probably is not the answer you want to hear.

The reason why `stable` is lagging behind can be read here: https://github.com/heroku/semver.io/issues/52#issuecomment-161832475

> semver.io's definition of stable is not always the absolute latest version of node: it's a reflection of what Heroku's team considers stable based on experience with customer apps running on the platform.
> 
> If  you want to use the latest release, consider using https://semver.io/node/unstable

So, I think `unstable` is what you want at the moment.

**Comment by icflorescu** [comment]
So, basically the answer provided by semver.io reflects Heroku's opinion, "based on experience with customer apps running on the platform" - whatever that means (?!). I'm runnings apps on Heroku for a couple of customers, one is still running on v4, the other is on v6. They're both "stable" in my opinion.  

`v4` is the "official LTS" version, `v6` is the latest (whether it's stable or unstable, that's open to debate), while `v5` is still the "latest stable" according to Heroku.

Hmmm. There's no right or wrong answer, I know, but in the end, which one should we default to for this cartridge?... Should we switch to unstable? Personally, I'm leaning towards it, since the cartridge name itself implies you'll be getting the **latest** (while you'll still be able to expressly lock to a specific version, of course).

I'll still be waiting for user feedback for a few more days before switching.

**Comment by timaschew** [comment]
+1 for using latest = version 6
It also become the new LTS in some months (October), see https://github.com/nodejs/LTS

**Comment by icflorescu** [comment]
Done in the last commit. By default, you'll now be getting:

![image](https://cloud.githubusercontent.com/assets/581999/16545825/25a0c78c-413f-11e6-8db5-070146f604ca.png)
