### ISSUE TITLE
node-gyp pakcage not installed

### ISSUE THREAD

**Issue by hamidjafari** [icflorescu/openshift-cartridge-nodejs#49]
does node-gyp package installed on this cartridge?
i've create an app with this cartridge and my app need "bcrypt" package witch needs "node-gyp".
and i've got an error that says there is not "node-gyp" package installed - so app can't start.
so i've have to change from "bcrypt" to "bcrypt-nodejs" thats not depends on node-gyp.
additionaly : i can't install node-gyp manually by type : "npm install node-gyp" - throw permision err
note : i've create another app with "mongodb" package that depends on node-gyp and this time the app worked

**Comment by icflorescu** [comment]
This is related to #12. There's also a note in the readme mentioning that native modules can't be built due to OpenShift's outdated `gcc` (4.4.7).

Unfortunately there's no way to "fix" this as long as OpenShift doesn't provide a newer `gcc`.
