### ISSUE TITLE
Error on clean install - OSE specific

### ISSUE THREAD

**Issue by engineersamuel** [icflorescu/openshift-cartridge-nodejs#50]
I fresh install of this cartridge currently fails with the error: `node: error while loading shared libraries: libuv.so.0.10: cannot open shared object file: No such file or directory`  I've used this cartridge a lot in the past without issue so I think this is something new.  To reproduce just 

`rhc app create someapp https://raw.githubusercontent.com/icflorescu/openshift-cartridge-nodejs/master/metadata/manifest.yml`

ssh in and type `node`

**Comment by engineersamuel** [comment]
I wonder if this is relevant? https://bugs.centos.org/view.php?id=10606

**Comment by engineersamuel** [comment]
There is definitely something up.  I ssh'd in to my gear and manually ran the top part of `bin/install` above update_nodejs.  Then I went line by line through update_nodejs in `lib/util` and it correctly installed nodejs.  It seems as though initial node binaries are borked.  I'm not sure where the issue is though.

**Comment by icflorescu** [comment]
Just did a quick `rhc app create` and everything seems to be fine.
Can you reproduce it again?
Maybe a temporary download/install glitch when you first tried it?

**Comment by engineersamuel** [comment]
Just tried it, definitely not working.  It says it successfully installed the node and npm, but immediately logging in to the gear and typing node fails:

```
➜  Projects rhc app create -g int_hosted_medium test https://raw.githubusercontent.com/icflorescu/openshift-cartridge-nodejs/master/metadata/manifest.yml
The cartridge 'https://raw.githubusercontent.com/icflorescu/openshift-cartridge-nodejs/master/metadata/manifest.yml' will be downloaded and installed

Application Options
-------------------
Domain:     subeng
Cartridges: https://raw.githubusercontent.com/icflorescu/openshift-cartridge-nodejs/master/metadata/manifest.yml
Gear Size:  int_hosted_medium
Scaling:    no

Creating application 'test' ... done

  Node.js  and NPM  installed.
Application is already running.

Waiting for your DNS name to be available ...
ect. ect.


➜  Projects ssh <the hash>@test-subeng.itos.redhat.com
[test-subeng.itos.redhat.com 576c39fdecdd5c8eef0010d2]\> node
node: error while loading shared libraries: libuv.so.0.10: cannot open shared object file: No such file or directory
```

The only thing I can think of is that I'm creating the gear against OSE 1.x.  This shouldn't make a difference as I've used your cartridge in the past against this env and it worked brilliantly, unless either something has changed in the OSE internally here, or something has changed in the cartridge that OSE doesn't quite like.  I guess at least I have a manual work around.  If I go and re-install the node at least once, it works fine after that with the auto-upgrading it seems.

**Comment by icflorescu** [comment]
Then it definitely must be an **OSE specific** issue. Unfortunately I don't have an OSE account to test on (nor did I ever considered this cartridge will ever be run on one :-), so if you manage to identify the exact problem, please do share it here and let me know if there's anything I can help with.

I'll leave the issue open, but I'll rename it for the sake of clarity.

Thanks for taking the time to look into it!

**Comment by icflorescu** [comment]
@engineersamuel - any news on this?

**Comment by icflorescu** [comment]
On the other hand, I guess things will change drastically when [Next Gen](https://www.openshift.com/devpreview/register.html) will replace the current cartridge framework.
I should probably consider building a Docker-based solution to replace this cartridge soon, right?
Any help would be more than welcome, of course ;-)

**Comment by nudoru** [comment]
Nothing to add here, but +1. I've just run into this.

**Comment by icflorescu** [comment]
Unfortunately I can't do much about it without official OpenShift support, and it's probably not worth it anyways since the entire cartridge mechanism will be made obsolete _soon_ (would be nice to know exactly **when**) by the new container platform.
