### ISSUE TITLE
503

### ISSUE THREAD

**Issue by simonnarang** [icflorescu/openshift-cartridge-nodejs#52]
Hi there,

I have a nodejs repo on github that I used when setting up the nodejs(latest) cartridge on open shift. When I run it locally it works fine, but when I host it with open shift I get a 503.

Thanks

**Comment by icflorescu** [comment]
You know you'll have to provide more info, right?

**Comment by simonnarang** [comment]
sure the github repo is [here](https://github.com/simonnarang/HambreBotServer)... I made it with WebStorm

**Comment by simonnarang** [comment]
It just replies to get requests with some data, very simple

**Comment by simonnarang** [comment]
replies with JSON to be more specific

**Comment by icflorescu** [comment]
The error is [on line 29](https://github.com/simonnarang/HambreBotServer/blob/master/bin/www#L29) in your www script. You're using the right port, but you should only listen on `process.env.OPENSHIFT_NODEJS_IP`, not all network interfaces.

Please note this is not a cartridge specific issue, and there's a [note in the readme](https://github.com/icflorescu/openshift-cartridge-nodejs#before-raising-issues) you should read first.

**Comment by simonnarang** [comment]
Thank you very very very much

**Comment by simonnarang** [comment]
@icflorescu really sorry to bother you but I couldn't find a solution anywhere else

I deleted the`|| 127.0.0.1` on line 15 and changed line 29 to `server.listen(process.env.OPENSHIFT_NODEJS_IP, port);` but I still get the same 503 error 😁!

Sorry and Thankyou again

**Comment by icflorescu** [comment]
Node.js [docs say](https://nodejs.org/api/http.html#http_server_listen_port_hostname_backlog_callback) port should be the first argument, host the 2nd.
