### ISSUE TITLE
Question: Does this cartridge work the mongodb module?

### ISSUE THREAD

**Issue by timaschew** [icflorescu/openshift-cartridge-nodejs#54]
You saying that native modules are not working, but you mention a custom cartridge for a new mongo db.

I wonder how the default driver for mogno: https://www.npmjs.com/package/mongodb
will work with this custom nodejs cartridge, because it has some native code (at least there is a .gyp file) or do you use a different mongo client?

**Comment by icflorescu** [comment]
I'm using the "default" driver in my apps and it does work, as the native dependency is entirely optional. Years ago, there used to be a difference in performance between the native JS parser/serializer and the pure-js one, but not anymore. See the discussion [here](https://github.com/Automattic/mongoose/issues/3436) for more info.

**Comment by icflorescu** [comment]
So feel free to use the [mongodb driver](https://www.npmjs.com/package/mongodb), it will work just fine with this [custom MongoDB cartridge](https://github.com/icflorescu/openshift-cartridge-mongodb), the [default OpenShift one](https://developers.openshift.com/databases/mongodb.html) or a connection to an external solution such as [mlab](https://mlab.com/).
