### ISSUE TITLE
support "stop" script

### ISSUE THREAD

**Issue by GochoMugo** [icflorescu/openshift-cartridge-nodejs#57]
Over the weekend I worked on an application that needed to be stopped in a more precise manner. It was handled using the ["stop" script](https://docs.npmjs.com/cli/stop). So I made some little tweaks on the control script to make it invoke the script rather than use `kill`.

Would you want me to push a PR your way?

**Comment by icflorescu** [comment]
Absolutely. I'm currently behind schedule in a commercial project, so won't have much time to dig into it over the the next few weeks, but I'll have a look at it and pull it asap.

Thanks for taking the time to contribute, it means a lot!...

There are around 200 installs per day for this cartridge, I'm dealing with lots of "how do I..." questions and requests for free support (though I clearly stated I have no commercial affiliation with RedHat), but so few people are willing to contribute back...
So any meaningful PRs are more than welcome.

Also, if you're planning on continuing to use Node.js on OpenShift in the future, bear in mind that they will deprecate the "cartridge" framework in favour of a Docker-based container system:

![image](https://cloud.githubusercontent.com/assets/581999/16810390/5b2fd5f6-492c-11e6-9d72-8331d0d56027.png)

I have no idea when will this happen, nor time to look into it at the moment, but in the end we're gonna have to replace this cartridge with a different solution. Hypothetically speaking, would you be interested in contributing?

**Comment by GochoMugo** [comment]
Definitely interested. I like that OpenShift provides free resources for developers, as they start out. And kinda not sooo commercialized.

I will get the PR done. We will deal with any changes as it comes. Let's cross that bridge when we get there! Until then...

**Comment by icflorescu** [comment]
Don't know why, but I have a feeling the resources will be "not so free" anymore starting with OpenShift NextGen... :-)

**Comment by GochoMugo** [comment]
I am hoping they will provide us with 3 free containers, in place of cartridges. Yeah, but I too feel that there's a rush in the Internet industry to commercialize as much as possible.

**Comment by icflorescu** [comment]
Merged. Thanks!
