### ISSUE TITLE
Instructions on how to set up

### ISSUE THREAD

**Issue by Ryu945** [icflorescu/openshift-cartridge-nodejs#59]
I am trying to set this up on Openshift.  The instructions are not that clear of what needs to be done to get a working directory.

**Comment by icflorescu** [comment]
What do you mean by _working directory_?

**Comment by icflorescu** [comment]
Can you please elaborate? Judging by GitHub stats, there are around 200 installs per day for this cartridge...

**Comment by icflorescu** [comment]
Will close this as non-constructive.
If you're interested in commercial support, drop me an email. If not, please refer to the readme section [Before raising issues](https://github.com/icflorescu/openshift-cartridge-nodejs#before-raising-issues) and the official [OpenShift documentation](https://access.redhat.com/documentation/en/openshift-online/).
