### ISSUE TITLE
Planned updates and potentially breaking changes

### ISSUE THREAD

**Issue by icflorescu** [icflorescu/openshift-cartridge-nodejs#6]
I'm thinking about adding a few potentially breaking changes and **I need your feedback** about this.

First, I'd like to rename the application entry-point from `start.js` to `index.js`, for better compatibility with development workflows / tools (i.e. lots of people are using `nodemon` in its "standard" configuration). I can't even remember why I used `start.js` initially, but it's kind of non-standard.

Second, I'd like to start the application (see [this line in the control script](https://github.com/icflorescu/openshift-cartridge-nodejs/blob/master/bin/control#L40)) with `node --use_strict`. Lots of people are now using ES6 / ES7 (with or without [babel](https://babeljs.io/)) and having to add `'use strict'` on top of every file is annoying.

And I'm also thinking about adding a better-looking application template in [this folder](https://github.com/icflorescu/openshift-cartridge-nodejs/tree/master/usr/template). Nothing too fancy because we have to avoid installing tens of `npm`s when provisioning the cartridge, but I'm thinking about displaying some useful info from [os](https://nodejs.org/api/os.html) on a nice-looking background (artwork suggestions and/or submissions are welcome :-) ).

Of course, the aforementioned changes won't affect existing deployments.

Looking forward for your feedback...

**Comment by wytesk133** [comment]
Maybe you can use `npm start` instead of hard coding the entry-point.

**Comment by AlexChesters** [comment]
:+1: for `npm start` as @wytesk133. Hard-coding the entry-point seems strange

**Comment by 4lejandrito** [comment]
Nodemon also tries `npm start` by default as well as other PAAS services like Heroku. 

+1 for `npm start` :)

**Comment by icflorescu** [comment]
Thank you all for your feedback!

I'm leaning towards `npm start` myself so I'll get @AlexChesters's [PR](https://github.com/icflorescu/openshift-cartridge-nodejs/pull/7) later today. I just have one small concern about it, see the discussion [here](https://github.com/icflorescu/openshift-cartridge-nodejs/pull/7).

If we'll find the memory usage unacceptable, we'll have to look for a way to "emulate" `npm start` using bash... which I find totally unappealing :-P

**Comment by icflorescu** [comment]
Finally managed to find some spare time for this; the "default" template looks a bit better now (imo).

![node-5-running-on-openshift](https://cloud.githubusercontent.com/assets/581999/11886158/ef202820-a52f-11e5-80a2-003b15541141.jpg)

Deploying a cartridge on OpenShift takes long enough already, that's why I wanted to avoid creating an [express](http://expressjs.com/en/index.html) or [koa](http://koajs.com/) application.

I've referred [Riot.js](http://riotjs.com/) and [superagent](https://github.com/visionmedia/superagent) from [jsdelivr](https://www.jsdelivr.com/) on the client-side, though. The client is polls the server and updates the "Uptime" and "Free Memory" rows once every 3 seconds... just for fun.

**Comment by RafaelSalguero** [comment]
Sorry if this is a dumb question but I can't find anything on google. There is a config file or any other way where I can disable `--use_strict` ? Google Cloud Storage API and node-forge doesn't run with strict mode

**Comment by icflorescu** [comment]
By default Node.js doesn't run in strict mode. If you're referring to the
default application template, it's running in strict mode because of line 8
in package.json:
https://github.com/icflorescu/openshift-cartridge-nodejs/blob/master/usr/template/package.json#L8

Feel free to adjust it how you see fit in your application.

Ionut-Cristian Florescu
+40.723.784.997 | ionut.florescu@gmail.com | linkedin.com/in/icflorescu
