### ISSUE TITLE
Updating an already deployed app

### ISSUE THREAD

**Issue by ghost** [icflorescu/openshift-cartridge-nodejs#62]
When creating an app there is a message in yellow letters that says:

> Downloaded cartridges do not receive updates automatically.

Their documentation is very vague and information is unrelated. Most people suggest deleting the app and recreating it just to update the cartridge.

Is there a way to update the cartridge manually?

**Comment by icflorescu** [comment]
To update **the cartridge** itself, no, I'm afraid there's no way of achieving this with community-cartridges. At least none that I know of... But if you have an idea, please, by all means, feel free to bring it up in a pull-request.

So, to clarify, hypothetically on rare occasions when we discover serious bugs or come up with major new features for the cartridge, recreating the app is the only way to go at the moment.

The Node.js version is, however, auto-updated on each deploy as needed, and that's what most people care about. So if your app is running and don't really **need** the new features, there's no need to update the cartridge (based on the idea _if it ain't broken, don't fix it_ :-). AFAIK there are apps running on this cartridge with more than 12 months up-time...

**Comment by ghost** [comment]
Ok! That makes a lot of sense! Thank you for the insight, I didn't realize that they updated on each deploy because I kept seeing version 5.x on my app instead of 6.x. I'll give it a shot.

**Comment by icflorescu** [comment]
I've made 6.x the cartridge default [last month](https://github.com/icflorescu/openshift-cartridge-nodejs/issues/48), so **if your instance is older than that**, just make sure to put something like `https://semver.io/node/resolve/6` in `NODE_VERSION_URL` and you'll get 6.3.1 installed on your next deployment.
