### ISSUE TITLE
No ".openshift" directory 

### ISSUE THREAD

**Issue by lynxionxs** [icflorescu/openshift-cartridge-nodejs#69]
When i do `git clone ssh://app...` there is no `.openshift` directory at the root.
Neither at $OPENSHIFT_REPO_DIR.
Just these

```
.git
static
utils
.eslintrc
app.js
package.json
start.js
```

I installed nodejs cartridge from the openshift web app.

**Comment by GochoMugo** [comment]
By default there's **no** `.openshift` directory. You, as the application developer, are responsible of populating it with action hooks, markers, etc. as you wish.

If you were looking for the directory containing Node.js binaries they can be found at path pointed by `$OPENSHIFT_DATA_DIR/.nodejs` (see [lib/util#L33](https://github.com/icflorescu/openshift-cartridge-nodejs/blob/4c2de4b91b3b2ea7609de05568157554f02e7a2d/lib/util#L33)). Also, the source files from this catridge can be found at `$OPENSHIFT_NODEJS_DIR` (@icflorescu where is this set?) .

**Comment by icflorescu** [comment]
As @GochoMugo said, it's up to the developer to add it.

@@GochoMugo - I don't remember where/how `$$OPENSHIFT_NODEJS_DIR` is set; it's probably OpenShift internal stuff...
