### ISSUE TITLE
Problem while creating my application (rhc command line)

### ISSUE THREAD

**Issue by ghost** [icflorescu/openshift-cartridge-nodejs#72]
While creating my application using rhc, I got this message: 

"Creating application 'bibus' ...
The cartridge manifest at
'http://reflector-support.kermit.rd.francetelecom.fr/reflect?u=https://raw.githubusercontent.com/icflorescu/openshift-cartridge-nodejs/master/metadata/manifest.yml'
took too long to retrieve."

Can you help me?

**Comment by icflorescu** [comment]
I really have no idea what "reflector-support.kermit.rd.francetelecom.fr" means...

**Comment by ghost** [comment]
Because in my compagny we use a cartridge reflector (like this one: https://github.com/smarterclayton/cartridge-reflector). Anyway, it's working now. Don't know what was the problem

**Comment by icflorescu** [comment]
So... is this still an issue?

**Comment by ghost** [comment]
Nope, closing it now ;)
