### ISSUE TITLE
HTTP error 503 while node.js is booting on a idle gear

### ISSUE THREAD

**Issue by amurzeau** [icflorescu/openshift-cartridge-nodejs#76]
Hi,

The control start only wait for node.js process to be spawned but don't wait for it to listen for incoming connections.
So when an idle gear is woken up, the first HTTP request reply too early and lead to 503 errors because of node.js not yet listening on port 8080.

Is the choice of `control start` to wait for the node.js process instead of the checking the 8080 port has a particular reason ?

For the record, the official node.js 0.10 cartridge wait for the 8080 to be listened.

Thanks

**Comment by GochoMugo** [comment]
I agree with you. It would be better to have us wait for the port to allow connections.

Are you going to work on a PR on this? Also, is the OpenShift platform still going to be in use in the near future?

**Comment by icflorescu** [comment]
About OpenShift "NextGen", based on Docker – looks like it's still in "developer preview", and unfortunately there's no word yet on GA, pricing, or free usage quotas... Which is kind of annoying and was the main reason I switched to ArubaCloud for my commercial projects. They don't have the generous "free usage for developers" policy that OpenShift used to have, but there's a cheap $1 / month plan where you can spin up your own flexible virtual server with **root access** and basically do what you want with it...

Back to the issue – it was a long time ago and I don't remember the exact reasons that led to the current form of `control start`, but checking the port sounds like a good idea, so, sure, feel free to PR :-)

**Comment by amurzeau** [comment]
Well, I didn't have this 503 error since then. And given the future of current OpenShift version, it seems not worth and risk to change the current behavior.

So I close this issue. If this become an issue again for me, I will eventually make a PR to handle that.

**Comment by icflorescu** [comment]
Yeah. Good call. Unfortunately. I mean, given the future of current OpenShift Online version.
