### ISSUE TITLE
Constant issue -- Cannot read property 'stop' of undefined

### ISSUE THREAD

**Issue by PassTheMayo** [icflorescu/openshift-cartridge-nodejs#77]
So I'm creating my own Node.js cartridge on OpenShift and it keeps spitting this out: [hastebin.com](https://hastebin.com/jeganumuga.js).

Here's my package.json: [JacobGunther12/DevelopmentBot](https://github.com/JacobGunther12/Development-Bot/blob/master/package.json).

So, what's the issue? I don't see any issues under my package.json...

**Comment by icflorescu** [comment]
Your `package.json` lacks a `start` entry; there's a note in the [repo README](https://github.com/icflorescu/openshift-cartridge-nodejs#notes) specifically mentioning this. Have a look at the [provided template](https://github.com/icflorescu/openshift-cartridge-nodejs/blob/master/usr/template/package.json) to see a working `package.json` format.
