### ISSUE TITLE
update current running applications NODE.js cartridge

### ISSUE THREAD

**Issue by newasmod** [icflorescu/openshift-cartridge-nodejs#80]
The way to update currently running in production application, that uses 'icflorescu/openshift-cartridge-nodejs/' .
Changing  .env/user_vars/NODE_VERSION_URL  to https://semver.io/node/stable doesn't works

**Comment by icflorescu** [comment]
Please try to `git push` again and see if it works.

**Comment by icflorescu** [comment]
Did it work for you after `git push`?

**Comment by newasmod** [comment]
Currentrly i do not have my repository locally, i cant push now. I have tried only reload app from openshift console and with rhc tool. Now i am in searching how can i clone my application repo from openshift , to try pushing it. Thank you!

**Comment by newasmod** [comment]
i have pushed , but nothin changed. 
I think that problem can be in tbah i have placed /NODE_VERSION_URL inside .env/user_vars ,
And update script looks for NODE_VERSION_URL inside .openshift/ folder. 
But in my app i have not .openshift/ folder with variables, inly .env folder. Is here a workaround?

**Comment by icflorescu** [comment]
The folder structure is imposed by OpenShift.
